export const GET_BLOGS = 'GET_BLOGS';

export const SHOW_ERROR = 'SHOW_ERROR';

export const CREATE_MESSAGE = 'CREATE_MESSAGE';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';

export const BOOK_CREATE_START = 'BOOK_CREATE_START';
export const BOOK_CREATE_SUCCESS = 'BOOK_CREATE_SUCCESS';
export const BOOK_CREATE_FAIL = 'BOOK_CREATE_FAIL';

export const BOOKS_FETCH_START = 'BOOKS_FETCH_START';
export const BOOKS_FETCH_SUCCESS = 'BOOKS_FETCH_SUCCESS';
export const BOOKS_FETCH_FAIL = 'BOOKS_FETCH_FAIL';

export const BOOK_FETCH_START = 'BOOK_FETCH_START';
export const BOOK_FETCH_SUCCESS = 'BOOK_FETCH_SUCCESS';
export const BOOK_FETCH_FAIL = 'BOOK_FETCH_FAIL';

export const BOOK_UPDATE_START = 'BOOK_UPDATE_START';
export const BOOK_UPDATE_SUCCESS = 'BOOK_UPDATE_SUCCESS';
export const BOOK_UPDATE_FAIL = 'BOOK_UPDATE_FAIL';

export const BOOK_DELETE_START = 'BOOK_DELETE_START';
export const BOOK_DELETE_SUCCESS = 'BOOK_DELETE_SUCCESS';
export const BOOK_DELETE_FAIL = 'BOOK_DELETE_FAIL';

export const CLEAR_BOOK = 'CLEAR_BOOK';
export const CLEAR_BOOKS = 'CLEAR_BOOKS';
export const CLEAR_BOOKS_STATE = 'CLEAR_BOOKS_STATE';

export const SEARCH_START = 'SEARCH_START';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAIL = 'SEARCH_FAIL';

export const CATEGORIES_FETCH_START = 'CATEGORIES_FETCH_START';
export const CATEGORIES_FETCH_SUCCESS = 'CATEGORIES_FETCH_SUCCESS';
export const CATEGORIES_FETCH_FAIL = 'CATEGORIES_FETCH_FAIL';
